Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.provider :virtualbox do |vb|
    vb.name = "Cassandra-Workstation"
    vb.memory = 4096
    vb.gui = true
  end

  config.vm.provision "shell" do |shell|
    shell.path  = "scripts/bootstrap.sh"
  end

end

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
